# Default initial positions for robot_description_3's ros2_control fake system

initial_positions:
  Lelbow_roll: 0
  Lshoulder_pitch: 0
  Lshoulder_roll: 0
  Relbow_roll: 0
  Rshoulder_pitch: 0
  Rshoulder_roll: 0
  Upper_body_joint: 0
  left_finger_1_j: 0
  riggt_finger_1_j: 0