controller_manager:
  ros__parameters:
    update_rate: 100

    torso_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


torso_controller:
  ros__parameters:
    joints:
      - Upper_body_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity


left_arm_controller:
  ros__parameters:
    joints:
      - Lshoulder_pitch
      - Lshoulder_roll
      - Lelbow_roll
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity


right_arm_controller:
  ros__parameters:
    joints:
      - Rshoulder_pitch
      - Rshoulder_roll
      - Relbow_roll
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity


left_gripper_controller:
  ros__parameters:
    joints:
      - left_gear_LG
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity


right_gripper_controller:
  ros__parameters:
    joints:
      - Right_gear_RG
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
